'use client';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, Bookmark, Check, Clock3, Pencil, Share2 } from 'lucide-react';
import { useState } from 'react';
import { useWiki } from './wiki-provider';
import { Markdown } from './markdown';
import { ArticleCard } from './feed';
import { formatDate, readingTime } from '@/lib/types';
export function ArticleView({id}:{id:string}){
 const {articles,ready,error,refresh,userId,saved,toggleSaved}=useWiki();const [shared,setShared]=useState(false);const [shareError,setShareError]=useState('');const article=articles.find(a=>a.id===id);
 if(!article)return <div className="empty-state"><h1>{!ready?'Загружаем статью…':error?'Не удалось загрузить статью':'Статья не найдена'}</h1><p>{error||'Возможно, ссылка изменилась или статья сохранена только в другом браузере.'}</p>{error&&<button className="button" onClick={()=>void refresh()}>Повторить загрузку</button>}<Link href="/" className="button dark">На главную</Link></div>;
 const related=articles.filter(a=>a.id!==id).sort((a,b)=>Number(b.category===article.category)-Number(a.category===article.category)).slice(0,3);
 return <div className="page-content article-page"><div className="article-nav"><Link href="/" className="text-link"><ArrowLeft size={16}/>Ко всем статьям</Link><div><button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.href);setShared(true);setTimeout(()=>setShared(false),2500);}catch{setShareError('Скопируйте адрес статьи из адресной строки.');}}}>{shared?<Check size={16}/>:<Share2 size={16}/>}<span>{shared?'Ссылка скопирована':'Поделиться'}</span></button><button className={`button ${saved.includes(id)?'saved-button':''}`} onClick={()=>toggleSaved(id)} aria-pressed={saved.includes(id)}><Bookmark size={16}/><span>{saved.includes(id)?'Сохранено':'Сохранить'}</span></button>{userId===article.author_id&&<Link className="button dark" href={`/write?edit=${id}`}><Pencil size={16}/>Редактировать</Link>}</div></div>{shareError&&<p role="status">{shareError}</p>}<header className="article-header"><span className="category-label">{article.category}</span><h1>{article.title}</h1><p className="article-lead">{article.excerpt}</p><div className="article-meta"><span className="author-avatar">{article.author_name.slice(0,1).toUpperCase()}</span><strong>{article.author_name}</strong><span>·</span><span>{formatDate(article.created_at)}</span><span>·</span><span><Clock3 size={14}/>{readingTime(article.content)} мин чтения</span></div></header>{article.cover&&<img className="article-cover" src={article.cover} alt={article.title}/>}<div className="reading-layout"><aside className="reading-note"><span className="tiny-star">✳</span><h3>Знания связаны</h3><p>Синие слова ведут к другим статьям. Следуйте за любопытством.</p><span>Обновлено<br/>{formatDate(article.updated_at)}</span></aside><Markdown content={article.content} currentId={article.id}/></div><section className="related"><div className="section-heading"><h2>Открытие за открытием</h2><Link href="/" className="text-link">Все статьи <ArrowUpRight size={16}/></Link></div><div className="article-grid">{related.map(a=><ArticleCard key={a.id} article={a}/>)}</div></section></div>;
}
