'use client';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Bookmark, Clock3, Grid2X2, List, Plus, Search } from 'lucide-react';
import { useWiki } from './wiki-provider';
import { categories, readingTime, type Article } from '@/lib/types';

export function ArticleCard({article}:{article:Article}){const {saved,toggleSaved}=useWiki();return <article className="article-card"><Link className="card-image" href={`/article/${article.id}`}>{article.cover?<img src={article.cover} alt="" loading="lazy"/>:<div className="cover-placeholder">D<span>✳</span></div>}<span className="image-category">{article.category}</span></Link><div className="card-body"><div className="card-title-row"><Link href={`/article/${article.id}`}><h3>{article.title}</h3></Link><ArrowUpRight size={20}/></div><p>{article.excerpt}</p><div className="card-bottom"><span><Clock3 size={13}/>{readingTime(`${article.excerpt}\n${article.content}`)} чтения</span><button className={`icon-button bookmark ${saved.includes(article.id)?'is-saved':''}`} onClick={()=>toggleSaved(article.id)} aria-label={saved.includes(article.id)?`Убрать «${article.title}» из сохранённого`:`Сохранить «${article.title}»`} aria-pressed={saved.includes(article.id)}><Bookmark size={18}/></button></div></div></article>;}
export function Feed(){
 const {articles,saved,userId,ready,error,refresh}=useWiki();const params=useSearchParams();const view=params.get('view');const query=params.get('q')||'';
 const [category,setCategory]=useState('Все статьи');const [layout,setLayout]=useState('grid');const [sort,setSort]=useState('new');const [limit,setLimit]=useState(9);
 const filtered=articles.filter(a=>(view!=='saved'||saved.includes(a.id))&&(view!=='mine'||a.author_id===userId)&&(category==='Все статьи'||a.category===category)&&`${a.title} ${a.excerpt} ${a.content}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru'))).sort((a,b)=>sort==='az'?a.title.localeCompare(b.title,'ru'):b.created_at.localeCompare(a.created_at));
 const home=!view&&!query;
 return <div className="feed page-content">{home&&<><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✳</span> МЕСТО, ГДЕ ЖИВЁТ ЛЮБОПЫТСТВО</div><h1>Мир знаний.<br/><span>Открытый каждому.</span></h1><p>Большие идеи начинаются с простого вопроса.<br/>Исследуйте новое и делитесь тем, что знаете.</p><div className="hero-actions"><Link href="/write" className="button dark">Поделиться знанием <ArrowUpRight size={17}/></Link><a href="#articles" className="text-link">Начать исследование <ArrowDown size={16}/></a></div><div className="hero-foot"><div className="mini-avatars"><i>А</i><i>М</i><i>Д</i><i>+</i></div><span>Разные люди. <strong>Общее любопытство.</strong></span></div></div><div className="hero-art" aria-hidden="true"><svg viewBox="0 0 420 360"><defs><pattern id="dots" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#bfc2b9"/></pattern></defs><rect width="420" height="360" fill="url(#dots)"/><circle cx="217" cy="173" r="119" fill="#dff47b"/><g fill="none" stroke="#252b25" strokeWidth="1.3"><circle cx="217" cy="173" r="119"/><ellipse cx="217" cy="173" rx="64" ry="119" transform="rotate(-28 217 173)"/><ellipse cx="217" cy="173" rx="27" ry="119" transform="rotate(-28 217 173)"/><ellipse cx="217" cy="173" rx="119" ry="41" transform="rotate(-28 217 173)"/><ellipse cx="217" cy="173" rx="119" ry="82" transform="rotate(-28 217 173)"/><ellipse cx="217" cy="173" rx="178" ry="52" transform="rotate(-28 217 173)"/></g><circle cx="59" cy="218" r="10" fill="#353b33"/><circle cx="350" cy="86" r="6" fill="#dff47b" stroke="#252b25"/><path d="M82 58v32M66 74h32M71 63l22 22M93 63L71 85" stroke="#252b25" strokeWidth="2"/><text x="297" y="298" fontSize="38" fill="#30372d">✳</text><rect x="267" y="224" width="117" height="39" rx="8" fill="#fff" stroke="#ddd" transform="rotate(-9 267 224)"/><text x="282" y="246" fontSize="12" fontFamily="Arial" fill="#333" transform="rotate(-9 267 224)">Всё взаимосвязано ↗</text><text x="66" y="316" fontSize="10" fontFamily="monospace" fill="#6e7467">ОТКРЫВАЙТЕ. СОЕДИНЯЙТЕ. СОЗДАВАЙТЕ.</text></svg></div></section></>}
 <section id="articles" className="articles-section"><div className="section-heading"><div><div className="eyebrow">{home?'ВАША СЛЕДУЮЩАЯ НАХОДКА':'ЛИЧНАЯ БИБЛИОТЕКА'}</div><h2>{query?`Поиск: «${query}»`:view==='saved'?'Сохранённое':view==='mine'?'Мои статьи':'Откройте что-то новое'} <span className="count">{filtered.length}</span></h2></div><div className="view-switch"><button aria-label="Показать сеткой" aria-pressed={layout==='grid'} className={layout==='grid'?'selected':''} onClick={()=>setLayout('grid')}><Grid2X2 size={17}/></button><button aria-label="Показать списком" aria-pressed={layout==='list'} className={layout==='list'?'selected':''} onClick={()=>setLayout('list')}><List size={19}/></button></div></div><div className="filter-row"><div className="category-tabs">{categories.map(c=><button key={c} className={category===c?'selected':''} onClick={()=>{setCategory(c);setLimit(9);}}>{c}</button>)}</div><select aria-label="Порядок статей" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Сначала новые</option><option value="az">По алфавиту</option></select></div>{error&&<div className="error-banner" role="alert">{error} <button onClick={()=>void refresh()}>Повторить</button></div>}{!ready?<div className="loading">Загружаем статьи…</div>:filtered.length?<div className={`article-grid ${layout==='list'?'list-layout':''}`}>{filtered.slice(0,limit).map(a=><ArticleCard key={a.id} article={a}/>)}</div>:<div className="empty-state"><Search size={35}/><h3>{view==='saved'?'Интересное останется с вами':view==='mine'?'Ваша первая статья — впереди':!articles.length?'Здесь начнётся история D WIKI':'Пока ничего не найдено'}</h3><p>{view==='saved'?'Нажмите на закладку рядом со статьёй, чтобы сохранить её.':view==='mine'?'Расскажите о том, что вас увлекает. Здесь будут ваши публикации.':!articles.length?'Станьте первым автором — поделитесь тем, что знаете.':'Попробуйте другой запрос или категорию.'}</p><Link className="button dark" href={view==='mine'||!articles.length?'/write':'/'}>{view==='mine'||!articles.length?'Написать статью':'Ко всем статьям'}<ArrowRight size={16}/></Link></div>}{filtered.length>limit&&<button className="button load-more" onClick={()=>setLimit(limit+9)}>Ещё немного открытий <ArrowDown size={16}/></button>}</section>{home&&<section className="contribute"><div className="contribute-star">✳</div><div><h2>Ваши знания кому-то нужны.</h2><p>Расскажите о том, что любите. Первую статью можно написать прямо сейчас.</p></div><Link className="button dark" href="/write"><Plus size={17}/>Создать статью</Link></section>}</div>;
}
