'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useWiki } from './wiki-provider';
import type { Article } from '@/lib/types';
export function Moderation(){
 const {articles,refresh,error:loadError}=useWiki();
 const [authenticated,setAuthenticated]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[deleting,setDeleting]=useState<Article|null>(null);
 async function api(path:string,method:string,body?:object){const response=await fetch(path,{method,cache:'no-store',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok){if(response.status===403)setAuthenticated(false);throw new Error(data.error||'Ошибка сервера.');}return data;}
 useEffect(()=>{api('/api/moder','GET').then(data=>setAuthenticated(data.authenticated)).catch(e=>setError(e.message)).finally(()=>setChecking(false));},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/moder','POST',{password});setPassword('');setAuthenticated(true);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function act(article:Article,action:string){setBusy(true);setError('');try{await api('/api/moder/articles','POST',{id:article.id,updated_at:article.updated_at,action});setDeleting(null);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(checking)return <div className="loading">Проверяем доступ…</div>;
 return <div className="page-content moder-page"><h1>Модерация D WIKI</h1>{!authenticated?<form className="moder-login" onSubmit={login}><p>Введите пароль для управления статьями.</p><label className="field-label" htmlFor="moder-password">Пароль</label><input id="moder-password" type="password" autoComplete="current-password" maxLength={256} value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy} className="button dark">{busy?'Проверяем…':'Войти'}</button></form>:<><div className="moder-controls"><input aria-label="Поиск статей для модерации" placeholder="Найти статью…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Статус модерации" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все статьи</option><option value="pending">Неподтверждённые</option><option value="approved">Подтверждённые</option></select><button disabled={busy} className="button" onClick={()=>void refresh()}>Обновить</button><button disabled={busy} className="button" onClick={async()=>{setBusy(true);try{await api('/api/moder','DELETE');setAuthenticated(false);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Выйти</button></div><p>После любого изменения текста подтверждение снимается: отредактированную версию нужно проверить заново.</p><div className="moder-list">{articles.filter(a=>a.title.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru'))&&(filter==='all'||(filter==='approved'?a.approved:!a.approved))).map(a=><article className="moder-row" key={a.id}><div><Link href={`/article/${a.id}`}><h2>{a.title}</h2></Link><p>{a.category} · {a.author_name}</p><span className={`moder-status ${a.approved?'approved':''}`}>{a.approved?'Подтверждена':'Ожидает проверки'}</span></div><div className="moder-actions"><Link className="button" href={`/article/${a.id}`}>Читать</Link><Link className="button" href={`/write?edit=${a.id}`}>Редактировать</Link><button disabled={busy} className="button" onClick={()=>void act(a,a.approved?'unapprove':'approve')}>{a.approved?'Снять подтверждение':'Подтвердить'}</button><button disabled={busy} className="button danger" onClick={()=>setDeleting(a)}>Удалить</button></div></article>)}</div>{!articles.length&&<p>Статей пока нет.</p>}</>}{(error||loadError)&&<p className="error-banner" role="alert">{error||loadError}</p>}{deleting&&<div className="modal-backdrop"><section className="link-modal" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">Удалить «{deleting.title}»?</h2><p>Статья исчезнет из общей ленты. Резервная копия останется в Redis на 30 дней.</p><div className="moder-actions"><button disabled={busy} className="button" onClick={()=>setDeleting(null)}>Отмена</button><button disabled={busy} className="button danger" onClick={()=>void act(deleting,'delete')}>{busy?'Удаляем…':'Удалить статью'}</button></div></section></div>}</div>;
}
