'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowUpRight, BookOpen, Bookmark, Compass, FileText, Code2, Menu, Plus, Search, Shuffle, X, Feather } from 'lucide-react';
import { useWiki } from './wiki-provider';
import { ThemeToggle } from './theme-toggle';
import { RecoveryNotice } from './recovery';
export function Shell({children}:{children:React.ReactNode}) {
 const {articles} = useWiki(); const router=useRouter(); const pathname=usePathname();const [menu,setMenu]=useState(false);const [search,setSearch]=useState('');
 const nav=[{href:'/',label:'Обзор',icon:Compass},{href:'/?view=saved',label:'Сохранённое',icon:Bookmark},{href:'/?view=mine',label:'Мои статьи',icon:FileText}];
 return <><aside className={`sidebar ${menu?'is-open':''}`}><Link className="brand" href="/" onClick={()=>setMenu(false)}><span className="brand-mark">D<span>✳</span></span><span>D WIKI<small>СВОБОДНАЯ ЭНЦИКЛОПЕДИЯ</small></span></Link><button className="mobile-close icon-button" onClick={()=>setMenu(false)} aria-label="Закрыть меню"><X/></button><div className="nav-caption">ВАШ МИР ЗНАНИЙ</div><nav>{nav.map(({href,label,icon:Icon},index)=><Link className={`nav-link ${index===0&&pathname==='/'?'active':''}`} href={href} key={href} onClick={()=>setMenu(false)}><Icon size={19}/>{label}{index===0&&<span className="nav-dot"/>}</Link>)}<button className="nav-link" disabled={!articles.length} onClick={()=>{if(!articles.length)return;router.push(`/article/${articles[Math.floor(Math.random()*articles.length)].id}`);setMenu(false);}}><Shuffle size={19}/>Случайная статья<ArrowUpRight size={14}/></button></nav><div className="sidebar-note"><span className="note-icon"><Feather size={23}/></span><h3>Знания растут,<br/>когда ими делятся.</h3><p>У каждого есть история,<br/>которую стоит рассказать.</p><Link href="/write" onClick={()=>setMenu(false)}>Написать статью <ArrowUpRight size={16}/></Link><div className="note-scribble">✳</div></div><div className="sidebar-footer"><span className="live-dot"/>Открыто для любопытных<Link href="/about">О проекте <ArrowUpRight size={13}/></Link><a href="https://github.com/AlexKraken444/D-WIKI" target="_blank" rel="noreferrer"><Code2 size={14}/> GitHub</a><small>© {new Date().getFullYear()} D WIKI</small></div></aside>{menu&&<button className="menu-backdrop" onClick={()=>setMenu(false)} aria-label="Закрыть меню"/>}<div className="workspace"><header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setMenu(true)} aria-label="Открыть меню"><Menu/></button><form className="searchbox" onSubmit={e=>{e.preventDefault();router.push(`/?q=${encodeURIComponent(search)}`);}}><Search size={18}/><input aria-label="Поиск статей" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Что вам интересно сегодня?"/><kbd>↵</kbd></form><ThemeToggle/><span className="topbar-label"><span className="live-dot"/>Знания без границ</span><Link className="button dark top-create" href="/write"><Plus size={17}/><span>Создать статью</span></Link><Link href="/?view=mine" className="avatar" aria-label="Мои статьи">ВЫ</Link></header><RecoveryNotice/><main>{children}</main><footer className="page-footer"><span>D WIKI <span className="muted">— мир интереснее, чем кажется.</span></span><Link href="/about">Создаём вместе <ArrowUpRight size={14}/></Link></footer></div></>;
}

